== Readme

This site is created using link:https://middlemanapp.com/basics/build-and-deploy[middleman].

Middleman is a Ruby gem that uses the information in `config.rb` to build the html pages, as well as resize the images to a maximum of 1080 pixels and does some other processing.

The text of the site, as well as the site layout is set in data\site_info.yml

== Adding photos and building the HTML for local testing

You can just drop images into the correct folder in 'originals' and do a local build by:

----
middleman build
----

Or alternately, you can add more information (date, medium, dimensions) by editing the Elsworth_Artworks_Catalog.csv file.

=== Progress pictures

If a folder with the same name is found, all images in that folder will be used to create a "Progress" link on that image's page. Again, more information can be added to the .csv file if desired.

=== Deploying to the website

In the terminal, cd to this folder and type:

----
> middlman deploy
----


=== To Do

The Mac invisible .DS_store files should not be copied to the FTP site.